---

- name: Make sure the configuration include directory exists
  file:
    path:    '{{ item }}'
    owner:   '{{ zabbix_agent__service_user }}'
    group:   '{{ zabbix_agent__service_group }}'
    mode:    0750
    recurse: yes
    state:   directory
  with_items:
    - '{{ zabbix_agent__conf_include_directory }}'
    - '{{ zabbix_agent__userparameters_directory }}'

- name: Create custom scripts directory
  file:
    path:  '{{ item }}'
    owner: root
    group: root
    mode:  0755
    state: directory
  with_items:
    - '{{ zabbix_agent__custom_scripts_directory }}'

- name: Update main configuration file
  template:
    src:   'zabbix_agentd.conf.j2'
    dest:  '{{ zabbix_agent__conf_file }}'
    owner: '{{ zabbix_agent__service_user }}'
    group: '{{ zabbix_agent__service_group }}'
    mode:  0640
  notify: [ 'restart-zabbix-agent' ]

- name: Configure sudoers rights for zabbix-agent
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ zabbix_agent__service_user }} ALL='
    line: '{{ zabbix_agent__service_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: not zabbix_agent__sudo_use_sudoers_role|bool

- name: Configure sudoers rights for zabbix-agent
  include_role:
    name: sudoers
    tasks_from: sudo_rule
  vars:
    sudoers__sudo_rule:
      name: zabbix_agent_01
      users: '{{ zabbix_agent__service_user }}'
      hosts: ALL
      comment: 'Allow zabbix_agent to run any commands'
      commands:
        - commands: ALL
          run_as_user: ALL
          tags: NOPASSWD
      defaults:
        - defaults: '!requiretty'
          user: '{{ zabbix_agent__service_user }}'
      state: present
  when: zabbix_agent__sudo_use_sudoers_role|bool
