---

- name: Make sure the configuration include directory exists
  file:
    path:  '{{ zabbix_agent__conf_include_directory }}'
    mode:  0755
    state: directory

- name: Update main configuration file
  template:
    src:   'zabbix_agentd.conf.j2'
    dest:  '{{ zabbix_agent__conf_file }}'
    owner: root
    group: '{{ zabbix_common__service_group }}'
    mode:  0640
  notify: [ 'restart-zabbix-agent' ]
